medicamento:
    resource: "@CipenMedicamentoBundle/Resources/config/routing.yml"
    prefix:   /medicamento

comun_comun:
    resource: "@ComunComunBundle/Resources/config/routing.yml"
    prefix:   /

cipen_diagnostico:
    resource: "@CipenDiagnosticoBundle/Resources/config/routing.yml"
    prefix:   /diagnostico

cipen_prestacion:
    resource: "@CipenPrestacionBundle/Resources/config/routing.yml"
    prefix:   /prestacion

cipen_paciente:
    resource: "@CipenPacienteBundle/Resources/config/routing.yml"
    prefix:   /paciente

cipen_obra_social:
    resource: "@CipenObraSocialBundle/Resources/config/routing.yml"
    prefix:   /obrasocial

cipen_internacion:
    resource: "@CipenInternacionBundle/Resources/config/routing.yml"
    prefix:   /internacion

cipen_diagnostico:
    resource: "@CipenDiagnosticoBundle/Resources/config/routing.yml"
    prefix:   /diagnostico

cipen_medico:
    resource: "@CipenMedicoBundle/Resources/config/routing.yml"
    prefix:   /medico

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
