parameters:
#    medicamento.example.class: Cipen\MedicamentoBundle\Example

services:
#    medicamento.example:
#        class: %medicamento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
