obra_social:
  pattern: /
  defaults: {_controller: "CipenObraSocialBundle:ObraSocial:listar"}

obra_social_crear:
    pattern:  /crear/
    defaults: { _controller: "CipenObraSocialBundle:ObraSocial:crear" }

obra_social_editar:
    pattern:  /{id}/editar/
    defaults: { _controller: "CipenObraSocialBundle:ObraSocial:editar" }

obra_social_eliminar:
    pattern:  /{id}/eliminar/
    defaults: { _controller: "CipenObraSocialBundle:ObraSocial:eliminar" }

obra_social_factura_editar:
    pattern:  /editar/{id}/factura/
    defaults: { _controller: "CipenObraSocialBundle:ObraSocial:editarFactura" }  

obra_social_unidad:
  pattern: /{obraSocialId}/unidad/
  defaults: {_controller: "CipenObraSocialBundle:Unidad:listar"}

obra_social_unidad_crear:
    pattern:  /{obraSocialId}/unidad/crear/
    defaults: { _controller: "CipenObraSocialBundle:Unidad:crear" }

obra_social_unidad_editar:
    pattern:  /{obraSocialId}/unidad/{id}/editar/
    defaults: { _controller: "CipenObraSocialBundle:Unidad:editar" }

obra_social_unidad_eliminar:
    pattern:  /{obraSocialId}/unidad/{id}/eliminar/
    defaults: { _controller: "CipenObraSocialBundle:Unidad:eliminar" }

obra_social_unidad_get_por_obra_social:
  pattern: /unidad/getporobrasocial
  defaults: {_controller: CipenObraSocialBundle:Unidad:getUnidadPorObraSocial}