parameters:
#    cipen_obra_social.example.class: Cipen\ObraSocialBundle\Example

services:
#    cipen_obra_social.example:
#        class: %cipen_obra_social.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
